"use strict";
/**
 * This file is generated by hand in order to bootstrap compiler development. It is intended to be an exact match to
 * compiled output.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports._capnpFileId = void 0;
exports._capnpFileId = BigInt("0x814e30b87b7df8bd");
//# sourceMappingURL=c++.capnp.js.map